name: voting_app
description: An e-voting app.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.1.6
  flutter_launcher_icons: ^0.9.2
  expandable: ^5.0.1

flutter_icons:
  image_path: "assets/launcherIcon.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
    - family: "DM Sans"
      fonts:
        - asset: fonts/DMSans-Bold.ttf
        - asset: fonts/DMSans-Medium.ttf
        - asset: fonts/DMSans-Regular.ttf
flutter_native_splash:
  color: "#011100"
  image: assets/Logo.png
  branding_mode: bottom